name: Brakeman action
author: Artem Kozaev
description: GitHub Action to run Brakeman static analysis which checks Ruby on Rails applications for security vulnerabilities.

inputs:
  flags:
    description: "Flags (list of available flags: https://github.com/presidentbeef/brakeman#basic-options)"

runs:
  using: docker
  image: docker://presidentbeef/brakeman
  args:
    - ${{ inputs.flags }}

branding:
  icon: alert-octagon
  color: black
